# Generated by Django 2.2.10 on 2021-05-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0002_auto_20210514_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='channel_title',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='created',
        ),
    ]
