# Generated by Django 2.2.10 on 2021-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0003_auto_20210514_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='publishedDateTime',
            new_name='publishedAt',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='video_id',
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
