# Generated by Django 3.2.3 on 2021-05-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0005_auto_20210514_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
