# Generated by Django 3.2.3 on 2021-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0006_alter_videos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
