# Generated by Django 3.2.3 on 2021-05-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0007_videos_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
