# Generated by Django 3.2.3 on 2021-05-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0008_alter_videos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
