# Generated by Django 3.2.3 on 2021-05-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0010_remove_videos_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='publishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnailsUrls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
